[package]
name = "truster"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"

#parsing
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }

# config
config = { version = "0.14", features = ["toml"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }

# Логирование (JSON structured logging)
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }

# args
clap = { version = "4.0", features = ["derive"] }

# shutdown logic
ctrlc = "3.5.2"

# http reqs
reqwest = "0.13.4"

# async
tokio = { version = "1.0", features = ["full"] }

# errors
anyhow = "1.0"
thiserror = "1.0"