name = "debug #0 (GET STATUS BY REQ + GET STATUS BY UID)"
base_url = "http://localhost:5401/api/v2.0"

[[endpoints]]
name = "GET STATUS BY UID"
url = "input/status/by-uid"
method = "GET"
rps = 1
source = "uids"

params = [
    { name = "documentType", index = 0 },
    { name = "uid", index = 1 },
    { name = "operatorId", index = 2 },
    { name = "requestType", index = 3 },
    { name = "isAllStatuses", index = 4 },
]

[[sources]]
name = "uids"
kind = "csv"
value = "profiles/debug_0_uids.csv"
